name: release
# 创建一个名为 release 的 workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
# 触发条件式 推送标签时触发

jobs:
# 工作内容如下
  goreleaser:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # 检出代码库
      with:
          fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.MYDDNS_TOKEN }}
      # 运行 run GoReleaser 这是一个自动化go项目发布工具
      # 如果推送标签时触发
      # 传递参数为 latest 和 --rm-dist

